### ISSUE TITLE
Min of EAD Results always 0

### ISSUE THREAD

**Issue by Brennan1994** [HydrologicEngineeringCenter/fda-model#115]
double sampleMin = r.ExpectedAnnualDamageResults.EADExceededWithProbabilityQ("residential", 1);

Always returns 0

**Comment by HenryGeorgist** [comment]
I believe this is from the constructor for histogram where the input data is null. We should remove the setting of min as zero. This is actually a combination of a bug in statistics and a way the histogram is used in fda. We should let the first added observation set the histogram min value so that the data has some say in the overall range. This current setup will yeild waaaaaay to many bins in all histograms used by fda and cause memory issues.
