### ISSUE TITLE
Add capability to specify curve type in curve metadata

### ISSUE THREAD

**Issue by AlexRyanUSACE** [HydrologicEngineeringCenter/fda-model#204]
Graphical curves (and possibly other applications) need to be able to accommodate decreasing X or Y value monotonicity. The default rules in paireddata enforce increasing monotonicity, which will result in resorted probabilities for graphical curves. There is currently commented out lines to handle decreasing monotonicity, but even if uncommented no current means to tell the paireddata object to expect that. Also currently the monotonicity logic is duplicated for both X and Y axes, but there will be cases (graphical discharge frequency curves currently) where increasing monotonicity should be expected on one axis (flow on the y axis in this case) and decreasing monotonicity on the other (probability on x).  

Recommend creating constructors for the curve metadata to handle these cases, and potentially another set of CurveTypeEnum values to handle cases in which increasing is expected on one axis and decreasing on the other.

**Comment by rnugent3** [comment]
I think the team once discussed using non-exceedance probability only. I may not have been good at maintaining that decision. In any case, if we do, then both X and Y should be increasing, all the time, right?

**Comment by HenryGeorgist** [comment]
We can adapt either way. How hard would it be to convert to non exceedance? Just a loop to do 1-x?

**Comment by AlexRyanUSACE** [comment]
I think that's probably true(?) although i would say if functionality to support both can be added fairly simply it may be worthwhile to do it, just for the sake of flexibility/stability. It seems like it's either allow for both and detect/handle appropriately, detect and throw an exception, or detect and convert from exceedance to non-exceedance, and since all would probably be about as much effort to implement i'd lean towards the one that adds flexibility. In particular as we have at least one production FDA model example in which exceedance was used.

**Comment by rnugent3** [comment]
It seems we need to add the following types to CurveTypesEnum: 
        -InverselyMonotonicallyIncreasing,
        -InverselyStrictlyMonotonicallyIncreasing,
       -InverselyMonotonicallyDecreasing,
        -InverselyStrictlyMonotonicallyDecreasing,
where increasing/decreasing refers to Yvals.

Are 9 different curve types a lot to track?

**Comment by rnugent3** [comment]
Thinking from a different perspective, what is the purpose of tracking curve types? I think the purpose is purely validation. I'm not tracking any methods that handle curve type nor plans for that. So we want to validate that the specified curves make sense before they go into the compute. 

What types do we expect? 

1. Strictly positive. All frequency functions. These functions must be strictly positive because frequency is non-exceedance probability and the functions represent CDFs. 

2. Weakly positive. System response curves, flow transforms, stage transforms, stage damage. These functions should be weakly positive because frequency functions are strictly positive, but flat regions could theoretically make sense. 

I suppose that flow and stage transforms could be weakly negative too - compose and other relevant methods should work fine because they don't depend on order. I think we've ruled out strictly negative because any frequency function will be a CDF on non-exceedance probability. 

@AlexRyanUSACE do you have any particular user story in mind motivating the capability to handle curve types other than (1) and (2)?

**Comment by rnugent3** [comment]
We decided during a meeting on 20 April 2022 that we will only handle strictly positive and weakly positive
