### ISSUE TITLE
EAD integration needs to be able to detect and handle descending X values

### ISSUE THREAD

**Issue by AlexRyanUSACE** [HydrologicEngineeringCenter/fda-model#206]
The descending X values in graphical curves will currently not work with the EAD integration as it does not know to step through in reverse order. The following code, beginning on line [207](https://github.com/HydrologicEngineeringCenter/fda-model/blob/9bf5f2159a03ef3ae9e6f4ca78d1223f9787cf96/fda-model/paireddata/PairedData.cs#L207) in the PairedData class, should correct the issue:

```c#
        public double integrate()
        {
            Boolean descending = false;
            if (Xvals.First() > Xvals.Last()) {
                descending = true;
            }

            double triangle;
            double square;
            double x1 = 1.0;
            if (descending)
            {
                x1 = 0;
            }
            double y1 = 0.0;
            double ead = 0.0;
            for (int i = 0; i < Xvals.Length; i++)
            {
                double xdelta = Xvals[i] - x1;
                square = xdelta * y1;
                triangle = ((xdelta) * (Yvals[i] - y1)) / 2.0;
                ead += square + triangle;
                x1 = Xvals[i];
                y1 = Yvals[i];
            }
            if (descending && x1 != 0)
            {
                ead *= -1;
                double xdelta = x1;
                ead += xdelta * y1;
            } else if (x1 != 1) 
            {
                double xdelta = 1 - x1;
                ead += xdelta * y1;
            }
            return ead;
        }
```

**Comment by rnugent3** [comment]
What do we think about converting curve types to all be the same? I feel like simplicity in the computational code (vs. validation logic, construction) is a priority.

**Comment by rnugent3** [comment]
@AlexRyanUSACE I like your solution. It is clean, concise, and easy to read. My preference would still be to run all calculations on non-exceeedance probability unless otherwise noted/for good reason. I can see things getting messy handling both measures of probability. I get confused switching back and forth between exceedance and non-exceedance. 

The damage frequency function is developed either from an analytical frequency function or a graphical frequency function. The PairedData analytical function is created from BootstrapToPairedData, a method that produces nonexceedance probabilities. The SamplePairedData method of the Graphical object now produces a PairedData object that also consists of nonexceedance probabilities.  I think we're good, then. What do you think?

**Comment by AlexRyanUSACE** [comment]
Yeah, i'm sold on the simplicity of just converting both to non-exceedance. That's a lot cleaner and still provides the same flexibility.

**Comment by rnugent3** [comment]
Great! Thank you.
